name: Heroku deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pokedex-app12"
          heroku_email: "hartzkaaa@gmail.com"
          healthcheck: "https://pokedex-app12.herokuapp.com/health"
          checkstring: "2"
          rollbackonhealthcheckfailed: true